language: go

go:
    - 1.2.2
    - 1.3.3
    - 1.4.2

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - go vet
    - go test -v -cover -bench .
    - $HOME/gopath/bin/goveralls -service=travis-ci
